### ISSUE TITLE
Is the Image watermark up-to-date?

### ISSUE THREAD

**Issue by Sunt-ing** [hzy312/Awesome-LLM-Watermark#5]
I guess that the image watermark for LLMs section in this list is not as up-to-date as the text watermark for LLMs. Some important work may be omitted. I'm not sure. But if so, I would appreciate it if you could complete that section.

**Comment by hzy312** [comment]
This image watermark section is contributed by another contributor.
My knowledge of this field is very limited.
Thanks for your attention to this repo.

**Comment by Sunt-ing** [comment]
Never mind. Thanks for your maintenance of this repo.
